server:
  port: 8084
  servlet:
    context-path:

spring:
  application:
    name: ms-users
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/CodeMastersElearning
      client:
        registration:
          keycloak:
            client-id: ms-users-client
            client-secret: Vnva8ic8ZZdIf7zSanuUbAXQcXWuaYQb
            scope:
              - openid
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/CodeMastersElearning
            token-uri: http://localhost:8080/realms/CodeMastersElearning/protocol/openid-connect/token

dh:
  keycloak:
    serverUrl: http://localhost:8080
    realm: CodeMastersElearning
    clientId: ms-users-client
    clientSecret: Vnva8ic8ZZdIf7zSanuUbAXQcXWuaYQb

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
